### ISSUE TITLE
freeze after exiting from fullscreen

### ISSUE THREAD

**Issue by aflahu** [ja2375/FluTube#13]

**Comment by ja2375** [comment]
Could you please give me more details to reproduce it?

**Comment by aflahu** [comment]
no debug console i can show to you, but if i downgrade to 0.6.2 not freezing again

freeze i mean
- after back from fullscreen video to be static(like image) 
- back button not work 
- sound still playing
- no appbar

**Comment by ja2375** [comment]
What flutter version are you using?
Does this occur with the lastest plugin version on pub?
Are you properly handling deviceOrientationAfterFullscreen and systemOverlaysAfterFullscreen?

**Comment by aflahu** [comment]
- v 0.8.1
- i had try 0.8.1, 0.8.0 still same. not others version i had tried more than 0.6.2
- not used

**Comment by ja2375** [comment]
In the first question i meant the flutter version, not the plugin version.

**Comment by aflahu** [comment]
oh sorry, v 1.7.8+hotfix.4

**Comment by ja2375** [comment]
Why are you closing this? Did you solve it?
