### ISSUE TITLE
The method 'play' was called on null.

### ISSUE THREAD

**Issue by Iamsdt** [ja2375/FluTube#24]
Code:
FluTube(
                  "https://www.youtube.com/watch?v=aNrqaOAt5P4",
                  autoPlay: false,
                  aspectRatio: 16 / 9,
                  looping: true,
                  onVideoStart: () {},
                  onVideoEnd: () {},
                )

Get this error:

The following NoSuchMethodError was thrown while handling a gesture:
The method 'play' was called on null.
Receiver: null
Tried calling: play()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      FluTubeState.build.<anonymous closure>.<anonymous closure> (package:flutube/src/flutube_player.dart:274:45)
#2      State.setState (package:flutter/src/widgets/framework.dart:1233:30)
#3      FluTubeState.build.<anonymous closure> (package:flutube/src/flutube_player.dart:273:27)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:14)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#3f122
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(207.6, 315.4)
  finalLocalPosition: Offset(34.9, 31.4)
  button: 1
  sent tap down

**Comment by rymesaint** [comment]
same with me

**Comment by aBuder** [comment]
same with me

**Comment by Maadhav** [comment]
Any Update?

**Comment by zjamshidi** [comment]
same with me

**Comment by Shajeel-Afzal** [comment]
The example app is crashing when we click on the play button.

**Comment by zjamshidi** [comment]
I switched to "youtube_player_flutter"

**Comment by geektutor** [comment]
Same with me. Would like an update on this

**Comment by ja2375** [comment]
Sorry, for now i don't have time to look into this issue. If anyone wants to help, PRs are welcome :)
