### ISSUE TITLE
Error playing video on iOS

### ISSUE THREAD

**Issue by tobacomachine** [ja2375/FluTube#3]
Hello and first of all give thanks for this fantastic project.
I've been experiencing a problem playing video on iOS. Audio and playback progresses correctly but the video can not be seen, it is transparent.
In Android everything works correctly.
Thanks again.

**Comment by ja2375** [comment]
Hello,
Thank you :)
Are you using the iOS simulator? Videos will do exactly that on simulators.
It is required to test this plugin on real devices as simulators have bugs when rendering videos.

**Comment by ja2375** [comment]
Closing as no answer.
