### ISSUE TITLE
Android SDK Build Tools version 25.0.3 is ignored

### ISSUE THREAD

**Issue by roufroufrouf** [ja2375/FluTube#4]
WARNING: The specified Android SDK Build Tools version (25.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.

**Comment by ja2375** [comment]
Android SDK build tools v25.0.3 is outdated. You should use 28.0.3 instead.
Always tend to use the latest version, otherwise you will run into issues. 
Google play store, for example, requires apps to target API 27+ as of now.
