### ISSUE TITLE
Player crashes with InvalidResponseCodeException sometimes

### ISSUE THREAD

**Issue by PiN73** [ja2375/FluTube#6]
I tried to play example video. It works well, but about in 5% cases it prints the following exception
```
E/ExoPlayerImplInternal(25866): Source error.
E/ExoPlayerImplInternal(25866): com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
E/ExoPlayerImplInternal(25866): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
E/ExoPlayerImplInternal(25866): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(25866): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal(25866): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(25866): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(25866): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(25866): 	at java.lang.Thread.run(Thread.java:764)
```
and the video is loading infinitely showing on-screen error
<img src="https://user-images.githubusercontent.com/18294052/54884803-34354000-4e86-11e9-95c4-fed233da88df.png" height="400">

[Full output when video is crashed](https://gist.github.com/PiN73/ed61d04fd6a4d80b53f7d5b18ad0e66b)

[Output when video works](https://gist.github.com/PiN73/6691815041113cf59dbbdb99fafab20d)

Tried on different networks, different emulators and physical devices, debug and release versions.

**Comment by PiN73** [comment]
Just made number of tests (launch app, press play, wait until playing started or error occurred, close app, repeat). Used the following parameters
```
FluTube(
  'https://www.youtube.com/watch?v=nPt8bK2gbaU',
  aspectRatio: 16 / 9,
  autoInitialize: true,
)
```
the result is `++++++++-+-++---++-++++++-++++-+` (`+` means worked, `-` means error)

**Comment by ja2375** [comment]
I'm aware of this. But unfortunately i think there is not too much i can do since this error occurs in the video_player plugin :(
I hope they will fix it one day...
I know it is not a flutube error because i did some debug and all URLs are loading well before creating the player, but it sometimes just crashes because, i believe, there is a race condition somewhere in the video_player plugin code.
Sorry not to be more helpful. If you know what the error is and where it happens, you could open an issue in the video_player plugin repo.

**Comment by PiN73** [comment]
So it is not related to copyrighted videos and encryption? From readme:
> PLEASE NOTE: Embedding copyrighted videos is actually not possible.

**Comment by ja2375** [comment]
Nope. This error happens with all videos.
If you try to embed a copyrighted video, it won't play at anytime. No matter if you retry.

**Comment by PiN73** [comment]
OK, thank you for explanation

**Comment by ja2375** [comment]
You are welcome :)
